--------------------------------------------------------
--  File created - Monday-November-26-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEVICES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SMARTLOCK"."DEVICES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EVENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SMARTLOCK"."EVENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SMARTLOCK"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DEVICES
--------------------------------------------------------

  CREATE TABLE "SMARTLOCK"."DEVICES" 
   (	"ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENTS
--------------------------------------------------------

  CREATE TABLE "SMARTLOCK"."EVENTS" 
   (	"ID" NUMBER(*,0), 
	"USER_ID" NUMBER(*,0), 
	"DEVICE_ID" NUMBER(*,0), 
	"EVENT" VARCHAR2(25 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"EVENT_TIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "SMARTLOCK"."USERS" 
   (	"ID" NUMBER(*,0), 
	"EMAIL" VARCHAR2(256 BYTE), 
	"PASSWORD" VARCHAR2(256 BYTE), 
	"TOKEN" VARCHAR2(256 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SMARTLOCK.DEVICES
SET DEFINE OFF;
Insert into SMARTLOCK.DEVICES (ID,USER_ID,NAME) values (3,2,'Device 1');
Insert into SMARTLOCK.DEVICES (ID,USER_ID,NAME) values (4,2,'Device 2');
REM INSERTING into SMARTLOCK.EVENTS
SET DEFINE OFF;
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (2,2,3,'OPEN','Lock opened',to_timestamp('11-NOV-18 02.28.35.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (3,2,3,'CLOSE','Lock has closed',to_timestamp('11-NOV-18 02.28.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (4,2,4,'ERROR','Lost connection to device',to_timestamp('11-NOV-18 02.28.44.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (5,2,3,'OPEN','Test',to_timestamp('11-NOV-18 05.07.28.619000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (6,2,3,'OPEN','Test',to_timestamp('11-NOV-18 05.09.37.891000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (21,2,4,'TEST','Test action 5',to_timestamp('20-NOV-18 08.23.35.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (22,2,4,'TEST','Test action',to_timestamp('20-NOV-18 08.26.25.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (23,2,4,'TEST','Test action 4',to_timestamp('20-NOV-18 08.27.00.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (24,2,4,'TEST','Test action 4',to_timestamp('20-NOV-18 08.29.12.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (25,2,3,'open','test',to_timestamp('25-NOV-18 08.24.23.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (26,2,3,'open','open',to_timestamp('25-NOV-18 08.47.37.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (27,2,3,'CONNECT','Device connected',to_timestamp('25-NOV-18 10.08.48.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (28,2,3,'DISCONNECT','Device disconnected',to_timestamp('25-NOV-18 10.10.18.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (29,2,3,'CONNECT','Device connected',to_timestamp('25-NOV-18 10.13.49.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (30,2,3,'DISCONNECT','Device disconnected',to_timestamp('25-NOV-18 10.15.34.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (31,2,3,'open','open',to_timestamp('25-NOV-18 10.15.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (32,2,3,'open','open',to_timestamp('25-NOV-18 10.15.41.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (33,2,3,'open','open',to_timestamp('25-NOV-18 10.15.42.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (34,2,3,'open','open',to_timestamp('25-NOV-18 10.15.42.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (35,2,3,'CONNECT','Device connected',to_timestamp('25-NOV-18 10.17.13.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
Insert into SMARTLOCK.EVENTS (ID,USER_ID,DEVICE_ID,EVENT,DESCRIPTION,EVENT_TIME) values (36,2,3,'DISCONNECT','Device disconnected',to_timestamp('25-NOV-18 10.17.27.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'));
REM INSERTING into SMARTLOCK.USERS
SET DEFINE OFF;
Insert into SMARTLOCK.USERS (ID,EMAIL,PASSWORD,TOKEN) values (2,'alexbotici@gmail.com','$2a$10$XdJxfO/gJgXRajBfGmVCGOvnJGCHT0laMPT4OTnMRpmp0BJvIZvPC',null);
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTLOCK"."USERS_PK" ON "SMARTLOCK"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEVICES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTLOCK"."DEVICES_PK" ON "SMARTLOCK"."DEVICES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTLOCK"."EVENTS_PK" ON "SMARTLOCK"."EVENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEVICES_USERS
--------------------------------------------------------

  CREATE INDEX "SMARTLOCK"."DEVICES_USERS" ON "SMARTLOCK"."DEVICES" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEVICES_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTLOCK"."DEVICES_UK1" ON "SMARTLOCK"."DEVICES" ("USER_ID", "NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_EMAIL
--------------------------------------------------------

  CREATE INDEX "SMARTLOCK"."USERS_EMAIL" ON "SMARTLOCK"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger DEVICES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SMARTLOCK"."DEVICES_TRG" 
BEFORE INSERT ON DEVICES 
FOR EACH ROW
BEGIN
  SELECT DEVICES_SEQ.nextval
  INTO :new.id
  FROM dual;
END;
/
ALTER TRIGGER "SMARTLOCK"."DEVICES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EVENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SMARTLOCK"."EVENTS_TRG" 
BEFORE INSERT ON EVENTS
FOR EACH ROW
BEGIN
  SELECT EVENTS_SEQ.nextval
  INTO :new.id
  FROM dual;
END;
/
ALTER TRIGGER "SMARTLOCK"."EVENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SMARTLOCK"."USERS_TRG" 
BEFORE INSERT ON USERS
FOR EACH ROW
BEGIN
  SELECT USERS_SEQ.nextval
  INTO :new.id
  FROM dual;
END;
/
ALTER TRIGGER "SMARTLOCK"."USERS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table DEVICES
--------------------------------------------------------

  ALTER TABLE "SMARTLOCK"."DEVICES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SMARTLOCK"."DEVICES" ADD CONSTRAINT "DEVICES_UK1" UNIQUE ("USER_ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SMARTLOCK"."DEVICES" ADD CONSTRAINT "DEVICES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SMARTLOCK"."DEVICES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SMARTLOCK"."DEVICES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "SMARTLOCK"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SMARTLOCK"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SMARTLOCK"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SMARTLOCK"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "SMARTLOCK"."EVENTS" MODIFY ("EVENT_TIME" NOT NULL ENABLE);
  ALTER TABLE "SMARTLOCK"."EVENTS" ADD CONSTRAINT "EVENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SMARTLOCK"."EVENTS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SMARTLOCK"."EVENTS" MODIFY ("EVENT" NOT NULL ENABLE);
  ALTER TABLE "SMARTLOCK"."EVENTS" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "SMARTLOCK"."EVENTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "SMARTLOCK"."EVENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DEVICES
--------------------------------------------------------

  ALTER TABLE "SMARTLOCK"."DEVICES" ADD CONSTRAINT "DEVICES_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SMARTLOCK"."USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "SMARTLOCK"."EVENTS" ADD CONSTRAINT "EVENTS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SMARTLOCK"."USERS" ("ID") ENABLE;
  ALTER TABLE "SMARTLOCK"."EVENTS" ADD CONSTRAINT "EVENTS_FK2" FOREIGN KEY ("DEVICE_ID")
	  REFERENCES "SMARTLOCK"."DEVICES" ("ID") ENABLE;
